FROM ghcr.io/coqui-ai/tts-cpu

ARG model_version=main

RUN apt-get update && \
    apt-get install -y --no-install-recommends curl
RUN mkdir -p /root/.local/share/wav && \
    mkdir -p /root/.local/share/tortoise/models && \
    mkdir -p /root/.local/share/tts/tts_models--multilingual--multi-dataset--xtts_v2 && \
    curl -sSLo /root/.local/share/tts/tts_models--multilingual--multi-dataset--xtts_v2/model.pth https://coqui.gateway.scarf.sh/hf-coqui/XTTS-v2/${model_version}/model.pth && \
    curl -sSLo /root/.local/share/tts/tts_models--multilingual--multi-dataset--xtts_v2/config.json https://coqui.gateway.scarf.sh/hf-coqui/XTTS-v2/${model_version}/config.json && \
    curl -sSLo /root/.local/share/tts/tts_models--multilingual--multi-dataset--xtts_v2/vocab.json https://coqui.gateway.scarf.sh/hf-coqui/XTTS-v2/${model_version}/vocab.json && \
    curl -sSLo /root/.local/share/tts/tts_models--multilingual--multi-dataset--xtts_v2/hash.md5 https://coqui.gateway.scarf.sh/hf-coqui/XTTS-v2/${model_version}/hash.md5 && \
    curl -sSLo /root/.local/share/tts/tts_models--multilingual--multi-dataset--xtts_v2/speakers_xtts.pth https://coqui.gateway.scarf.sh/hf-coqui/XTTS-v2/${model_version}/speakers_xtts.pth

ENV COQUI_TOS_AGREED=1
ENV TTS_HOME=/root/.local/share
ENV TORTOISE_MODELS_DIR=/root/.local/share/tortoise/models

COPY TTS/ /root/TTS/

ENTRYPOINT ["python3", "TTS/server/freechat_tts_server.py"]
CMD ["--model_name", "tts_models/multilingual/multi-dataset/xtts_v2", "--model_path", "/root/.local/share/tts/tts_models--multilingual--multi-dataset--xtts_v2", "--config_path", "/root/.local/share/tts/tts_models--multilingual--multi-dataset--xtts_v2/config.json", "--speakers_file_path", "/root/.local/share/tts/tts_models--multilingual--multi-dataset--xtts_v2/speakers_xtts.pth", "--vocab_path", "/root/.local/share/tts/tts_models--multilingual--multi-dataset--xtts_v2/vocab.json", "--show_details", "true"]
