ARG BASE_IMAGE=xxxxrt666/gpt-sovits:latest-cu128
FROM ${BASE_IMAGE}

ARG MODEL_REPO=HF
ENV MODEL_REPO=${MODEL_REPO}

# install python dependencies
RUN bash /workspace/GPT-SoVITS/install.sh --device CPU --source ${MODEL_REPO}
COPY data/ /workspace/GPT-SoVITS/
RUN pip install --no-input --no-cache-dir -r /workspace/GPT-SoVITS/server-requirements.txt
RUN conda clean --all && pip cache purge && apt-get clean

ENTRYPOINT ["python", "/workspace/GPT-SoVITS/server.py"]
CMD ["--bind_addr", "0.0.0.0",\
 "--tts_config", "/workspace/GPT-SoVITS/tts_infer.yaml",\
 "--device", "cpu",\
 "--is_half", "false",\
 "--version", "v4",\
 "--enable_aliyun_tts"]