ARG BASE_IMAGE=xxxxrt666/gpt-sovits:latest-cu128
FROM ${BASE_IMAGE}

# install python dependencies
RUN rm -rf /workspace/GPT-SoVITS/GPT_SoVITS/pretrained_models && \
  rm -rf /workspace/GPT-SoVITS/GPT_SoVITS/text/G2PWModel && \
  rm -rf /workspace/GPT-SoVITS/tools/asr/models && \
  rm -rf /workspace/GPT-SoVITS/tools/uvr5/uvr5_weights && \
  ln -s /workspace/models/pretrained_models /workspace/GPT-SoVITS/GPT_SoVITS/pretrained_models && \
  ln -s /workspace/models/G2PWModel /workspace/GPT-SoVITS/GPT_SoVITS/text/G2PWModel && \
  ln -s /workspace/models/asr_models /workspace/GPT-SoVITS/tools/asr/models && \
  ln -s /workspace/models/uvr5_weights /workspace/GPT-SoVITS/tools/uvr5/uvr5_weights \

# install python dependencies
COPY data/ /workspace/GPT-SoVITS/
RUN pip install --no-input --no-cache-dir -r /workspace/GPT-SoVITS/server-requirements.txt

ENTRYPOINT ["python", "/workspace/GPT-SoVITS/server.py"]
CMD ["--bind_addr", "0.0.0.0",\
 "--tts_config", "/workspace/GPT-SoVITS/tts_infer.yaml",\
 "--device", "cpu",\
 "--is_half", "false",\
 "--version", "v4",\
 "--enable_aliyun_tts"]