annotations:
  group: fun.freechat
autoscaling:
  enabled: false
cert:
  manager:
    namespace: cert-manager
    version: v1.16.1
deployment:
  enabled: true
  gpu:
    enabled: true
    type: 'nvidia'
    number: 1
image:
  repository: ghcr.io/coqui-ai/tts
extraArgs:
  - "--model_name"
  - "tts_models/multilingual/multi-dataset/xtts_v2"
  - "--use_cuda"
  - "true"
extraEnv:
  - name: TTS_HOME
    value: "data"
  - name: TORTOISE_MODELS_DIR
    value: "/root/data/tortoise/models"
  - name: COQUI_TOS_AGREED
    value: "1"
ingress:
  enabled: false
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: freechat-tts-letsencrypt-http01
  hosts:
    - host: tts.freechat.fun
      paths:
        - path: /
          pathType: Prefix
  tls:
    enabled: false
pdb:
  create: true
  minAvailable: ''
  maxUnavailable: ''
podSecurityContext:
  fsGroup: 10000
persistence:
  enabled: false
  accessModes: [ ReadWriteOnce ]
  storage: 60Gi
replicaCount: 1
livenessProbe:
  enabled: false
  failureThreshold: 60
  tcpSocket:
    port: http   
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5
readinessProbe:
  enabled: true
  failureThreshold: 6
  tcpSocket:
    port: http   
  initialDelaySeconds: 30
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 3
resources:
  requests: {}
  limits: {}
service:
  port: 5002
  type: ClusterIP
serviceAccount:
  create: true
  automount: false
